name: Shulker18
author: AtomicKill7
version: 1.0
main: newgkaan.shulker.Shulker

commands:
  shulker:
    description: 'Command for use Shulker18 app'


permissions:
  shulker.op:
    default: op
    description: 'Shulker18 command usage perm'